spring:
  aerospike:
    hosts: localhost:3000
  data:
    aerospike:
      namespace: test
      batch-write-size: 100
      create-indexes-on-startup: true
      index-cache-refresh-seconds: 3600
      keep-original-key-types: false
      query-max-records: 10
      server-version-refresh-seconds: 3600
      scans-enabled: false